// QT_FrontEnd/QT_FrontEnd/src/app/components/navbar/navbar.component.ts
import { Component, HostListener } from '@angular/core';
import { QUTIE_APPLY_URL } from '../../qutie.config';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
// The navbar shows nothing about sign-in state. Admins reach /login directly, and
// the signed-in controls live on the Codex page where publishing happens - so this
// component no longer needs the auth service at all.
export class NavComponent {
  isMobileMenuOpen = false;

  // Apply lives on Qutie - the navbar links straight there (no intermediate page).
  readonly applyUrl = QUTIE_APPLY_URL;

  toggleMobileMenu(): void {
    this.isMobileMenuOpen = !this.isMobileMenuOpen;
    // Prevent body scrolling when mobile menu is open
    document.body.style.overflow = this.isMobileMenuOpen ? 'hidden' : '';
  }

  closeMobileMenu(): void {
    if (this.isMobileMenuOpen) {
      this.isMobileMenuOpen = false;
      document.body.style.overflow = '';
    }
  }

  // Close mobile menu when window is resized to desktop size
  @HostListener('window:resize', ['$event'])
  onResize(event: any): void {
    if (window.innerWidth > 768 && this.isMobileMenuOpen) {
      this.closeMobileMenu();
    }
  }
}

<!--
  Structure and class names are shared with the Codex's navbar and styled by
  ../../../../shared/navbar.css. Keep the two in step: anything visual belongs in
  that file, not here. The mobile toggle below is Angular-only and keeps its own
  classes; nothing in this bar reflects sign-in state.
-->
<nav class="qt-nav">
  <div class="qt-nav__inner navbar-container">
    <!-- Logo on the left -->
    <div class="qt-nav__start logo">
      <a routerLink="/" class="qt-nav__brand">
        <img src="/assets/logo.png" alt="Quintessence Logo" class="qt-nav__logo" />
        <span class="qt-nav__wordmark">Quintessence</span>
      </a>
    </div>
    <!-- Mobile Menu Toggle -->
    <div class="mobile-toggle" (click)="toggleMobileMenu()">
      <i class="fas" [ngClass]="isMobileMenuOpen ? 'fa-times' : 'fa-bars'"></i>
    </div>
    <!-- Navigation Links - right aligned -->
    <ul class="qt-nav__links" [ngClass]="{'mobile-open': isMobileMenuOpen}">
      <li><a class="qt-nav__link" routerLink="/" routerLinkActive="qt-nav__link--active" [routerLinkActiveOptions]="{exact: true}" (click)="closeMobileMenu()">Home</a></li>
      <li><a class="qt-nav__link" [href]="applyUrl" target="_blank" rel="noopener" (click)="closeMobileMenu()">Apply</a></li>
      <li><a class="qt-nav__link" routerLink="/games" routerLinkActive="qt-nav__link--active" (click)="closeMobileMenu()">Games</a></li>
      <li><a class="qt-nav__link" routerLink="/roster" routerLinkActive="qt-nav__link--active" (click)="closeMobileMenu()">Roster</a></li>
      <!-- The Codex is a separate app served at /guides by the same nginx, not an
           Angular route - so this must stay a plain href (a real page load).
           routerLink would hand it to the SPA router, which would miss and fall
           through to the '**' redirect back to home. -->
      <li><a class="qt-nav__link" href="/guides/" (click)="closeMobileMenu()">Codex</a></li>
      <!-- Nothing here reflects sign-in state. Admins reach /login directly, and the
           only signed-in controls live on the Codex page, which is where publishing
           happens. The session itself is site-wide either way. -->
    </ul>
  </div>
</nav>

// codex/src/components/Navbar.tsx
import { Link } from "react-router-dom";
import { Logo } from "./Logo";
import { GameDropdown } from "./GameDropdown";

/**
 * Deliberately NOT styled with Tailwind. This uses the same markup and class names
 * as the Angular site's navbar, styled by the one stylesheet both apps load
 * (`shared/navbar.css`, pulled in from `src/index.css`).
 *
 * Keeping two parallel implementations in visual sync by hand did not hold - they
 * drifted on border width (0.8px vs 1px), blur radius, box-shadow and link padding.
 * If the bar needs to change, change it there and both halves follow.
 *
 * The game switcher is Codex-only and keeps its own styling. Sign-in deliberately
 * does NOT live here - it sits beside the search bar on the home page, where it is
 * actually relevant and where the signed-in state has room.
 */
export function Navbar() {
  return (
    <header className="qt-nav">
      <div className="qt-nav__inner">
        <div className="qt-nav__start">
          <Link to="/" className="qt-nav__brand">
            <Logo className="qt-nav__logo" />
            <span className="qt-nav__wordmark">
              Quintessence <span className="qt-nav__wordmark-sub">Codex</span>
            </span>
          </Link>

          <div className="hidden md:block">
            <GameDropdown />
          </div>
        </div>

        {/* Same five destinations as the Angular navbar. Plain hrefs, not router
            Links: everything except the Codex itself lives in the Angular app, so
            they have to be real page loads. */}
        <ul className="qt-nav__links">
          <li><a className="qt-nav__link" href="/">Home</a></li>
          <li>
            <a className="qt-nav__link" href="https://qutie.app/g/1137802734284832910/apply"
               target="_blank" rel="noopener">Apply</a>
          </li>
          <li><a className="qt-nav__link" href="/games">Games</a></li>
          <li><a className="qt-nav__link" href="/roster">Roster</a></li>
          <li><Link className="qt-nav__link qt-nav__link--active" to="/">Codex</Link></li>
        </ul>
      </div>
    </header>
  );
}
